### ISSUE TITLE
add a setting to automatically "cancel" if the URL is duplicated

### ISSUE THREAD

**Issue by rhuang** [noitcudni/google-webmaster-tools-bulk-outdated-content-removal#5] opened 2020-01-20 19:26 UTC
<img width="451" alt="Screen Shot 2020-01-20 at 11 25 15 AM" src="https://user-images.githubusercontent.com/1022385/72752648-9aa6ef80-3b77-11ea-84c8-12c3e8d92268.png">

Can you make it automatically click on "cancel"?

Took a really quick look at the code, maybe something like:
```
    } else if ($dialog.text().includes("A removal request for this URL has already been made.")) {
      clickWithWait(["div[role='dialog'] button div:contains('Cancel')"]);
    }
```

You could make it more sophisticated and retry a couple times before cancelling with settings to configure it, but personally for me, I would just like to request the "cancel" feature.

**Comment by noitcudni** [comment] 2020-01-20 21:24
Thanks for bringing that up to my attention.  I tried doing just that a while back, but that button is somehow implemented differently from all other buttons. A simple triggering of a click event didn't work. I'm going to give it another try soon. Please stay tuned.

**Comment by DanielRuf** [comment] 2020-04-18 10:27
Any updates on this? Can you need some help with this?

**Comment by noitcudni** [comment] 2020-04-18 21:05
I don't seem to be able to reproduce this anymore. If any of you can provide me a way to reproduce it that would be great. I have submitted the same URL multiple times.

**Comment by DanielRuf** [comment] 2020-04-18 21:44
I can still reproduce it with the code here in the repository. I have to manually click "cancel". Is the latest release and code of the extension here on GitHub?

**Comment by noitcudni** [comment] 2020-04-18 21:48
I'm in the process of rewriting it in clojurescript. Can you send me a URL that triggers this particular case?

**Comment by noitcudni** [comment] 2020-04-18 21:52
I guess what I'm asking for are the steps I need to take to reproduce it.  I submitted a URL and waited for awhile for google to do its thing. Then, I resubmitted the same exact URL, but it let me submit it again.

This is not the first time that I'm experiencing Google's removal tool behaving inconsistently.

**Comment by DanielRuf** [comment] 2020-04-18 21:58
It happens for every duplicate URL on myside. Try it with a csv which has the same URL twice or more in it to reproduce it. Maybe you have to switch to another Google account.

**Comment by noitcudni** [comment] 2020-04-18 22:02
I found an entry that has been removed from a different account. That did it for me.

**Comment by DanielRuf** [comment] 2020-04-18 22:14
<img width="452" alt="Bildschirmfoto 2020-04-18 um 12 25 58" src="https://user-images.githubusercontent.com/827205/79672474-95872a00-81d2-11ea-9777-b82a792226e5.png">

Looks like this, and then nothing happens. So it seems this is still not working.

**Comment by noitcudni** [comment] 2020-04-18 23:49
Yes, I'm well aware.

**Comment by DanielRuf** [comment] 2020-04-19 08:45
> I found an entry that has been removed from a different account. That did it for me.

I think I misunderstood this, sorry. So you can reproduce this now?

**Comment by DanielRuf** [comment] 2020-04-19 11:40
Currently testing, I think I know what the issue is. The script picks an old version / the previous dialog. Some sort of race condition.

**Comment by noitcudni** [comment] 2020-04-25 03:42
It's already fixed in the cljs version.

**Closed by noitcudni** 2020-04-25 03:42 UTC

**Comment by DanielRuf** [comment] 2020-04-25 08:32
Please link the commit that fixes this. It would be great if you would actually merge PRs.

**Comment by noitcudni** [comment] 2020-04-25 16:02
https://github.com/noitcudni/google-webmaster-tools-bulk-outdated-content-removal/commit/7d5a01c32150d3350cd0a6f9b9ee1a96b91d8e44

**Comment by DanielRuf** [comment] 2020-04-25 16:09
Thanks.
